# Generated by Django 5.0.1 on 2024-01-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=100)),
            ],
        ),
    ]
