# import pytesseract
# from PIL import Image
# import io

# def ocr_from_image(img):
#     img = Image.open(io.BytesIO(img))
#     text = pytesseract.image_to_string(img)
#     return text

# -*- coding: utf-8 -*-
"""unisnipp_gemini.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JqguW6zZXGR67GygUfDqXGR9d-gLowuV
"""

import pathlib
import textwrap

import google.generativeai as genai

from IPython.display import display
from IPython.display import Markdown
from google.colab import userdata


def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))


GOOGLE_API_KEY=userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)

import PIL.Image

img = PIL.Image.open('jk.jpg')
img

model = genai.GenerativeModel('gemini-pro-vision')

response = model.generate_content(["extract the text in proper way from this image", img], stream=True)
response.resolve()
to_markdown(response.text)

response1 = model.generate_content(["Understand what the extracted text is completely and format it in key-value pair with proper indentation", img], stream=True)
response1.resolve()

print(response1.text)