# Generated by Django 4.2.9 on 2024-01-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_ehr_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehr',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
