# Generated by Django 4.2.9 on 2024-02-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_ehr_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehr',
            name='translated_french',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ehr',
            name='translated_hindi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ehr',
            name='translated_mandarin',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ehr',
            name='translated_spanish',
            field=models.TextField(default=''),
        ),
    ]
