# Generated by Django 5.0.1 on 2024-01-10 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 4, 34, 54, 652107, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
