# Generated by Django 5.0.1 on 2024-01-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
