# Generated by Django 5.0.1 on 2024-01-17 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        ('users', '0003_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='family.family'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
