# Generated by Django 5.0.1 on 2024-01-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_fid_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(default=9999999999, max_length=15),
            preserve_default=False,
        ),
    ]
