# Generated by Django 5.0.1 on 2024-01-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_contact_no'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
